[project]
name = "weaviate-datahub"
version = "0.1.0"
description = ""
authors = [
    {name = "Mousa Becquerel",email = "m.sondoqah@becquerelinstitute.eu"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "pandasai (>=3.0.0b2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"